name: job_scraper
channels: 
   - defaults
   - conda-forge
dependencies: 
   - python=3.12
   - numpy
   - pandas
   - openpyxl
   - requests
   - beautifulsoup4
   - rapidfuzz
   - jupyter
   - ipykernel
   - nbconvert
